name: Run Python Script

on:
  push:
    branches:
      - main  # atau nama branch lain yang Anda gunakan

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Ganti x dengan versi Python yang Anda gunakan

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Jika ada file requirements.txt

    - name: Run script
      run: python sc.py
